#!/bin/bash
set -euo pipefail

whoami || true
id || true
sudo id || true

VERSION=${BUILDKITE_PLUGIN_GVISOR_VERSION:-'latest'}

ARCH=$(uname -m)
URL=https://storage.googleapis.com/gvisor/releases/release/${VERSION}/${ARCH}

wget \
    ${URL}/runsc \
    ${URL}/runsc.sha512 \
    ${URL}/containerd-shim-runsc-v1 \
    ${URL}/containerd-shim-runsc-v1.sha512

sha512sum -c runsc.sha512 -c containerd-shim-runsc-v1.sha512
rm -f *.sha512
chmod a+rx runsc containerd-shim-runsc-v1

mv runsc containerd-shim-runsc-v1 /usr/local/bin

/usr/local/bin/runsc install
systemctl reload docker

# TODO(andrew-d): remove me after testing
docker run --rm --runtime=runsc hello-world
